/**
 * ISO 20022 Bank Transaction Code (BTC) lookup tables.
 *
 * English source: BTC_Codification_30October2023.xls published by ISO 20022 RA.
 * https://www.iso20022.org/catalogue-messages/additional-content-messages/external-code-sets
 *
 * German source: UniCredit "Geschäftsvorfall- und Rückgabecodes" (August 2022).
 * German descriptions cover the SEPA / German banking combinations actually used
 * by UniCredit; not all 250 SubFamily codes have a German equivalent.
 *
 * Hierarchy:
 *   Domain     → funds_code        (finance_transaction.funds_code)
 *   Family     → transaction_type  (finance_transaction.transaction_type)
 *   SubFamily  → transaction_code  (finance_transaction.transaction_code)
 *
 * The three levels are independently usable for generic category labels.
 * For exact German booking texts, use `lookupBtcCombination(domain, family, subfamily)`,
 * which looks up the specific (Domain/Family/SubFamily) triple from the UniCredit table.
 */

/** ISO BTC Domain codes (ExternalBankTransactionDomain1Code). */
export const BTC_DOMAINS: Record<string, string> = {
  ACMT: "Account Management",
  CAMT: "Cash Management",
  CMDT: "Commodities",
  DERV: "Derivatives",
  FORX: "Foreign Exchange",
  LDAS: "Loans, Deposits & Syndications",
  PMET: "Precious Metal",
  PMNT: "Payments",
  SECU: "Securities",
  TRAD: "Trade Services",
  XTND: "Extended Domain",
};

/** ISO BTC Family codes (ExternalBankTransactionFamily1Code). */
export const BTC_FAMILIES: Record<string, string> = {
  ACCB: "Account Balancing",
  ACOP: "Additional Miscellaneous Credit Operations",
  ADOP: "Additional Miscellaneous Debit Operations",
  BLOC: "Blocked Transactions",
  CAPL: "Cash Pooling",
  CASH: "Miscellaneous Securities Operations",
  CCRD: "Customer Card Transactions",
  CLNC: "Clean Collection",
  CNTR: "Counter Transactions",
  COLC: "Custody Collection",
  COLL: "Collateral Management",
  CORP: "Corporate Action",
  CSLN: "Consumer Loans",
  CUST: "Custody",
  DCCT: "Documentary Credit",
  DLVR: "Delivery",
  DOCC: "Documentary Collection",
  DRFT: "Drafts",
  FTDP: "Fixed Term Deposits",
  FTLN: "Fixed Term Loans",
  FTUR: "Futures",
  FWRD: "Forwards",
  GUAR: "Guarantees",
  ICCN: "Issued Cash Concentration Transactions",
  ICDT: "Issued Credit Transfers",
  ICHQ: "Issued Cheques",
  IDDT: "Issued Direct Debits",
  IRCT: "Issued Real-Time Credit Transfers",
  LACK: "Lack",
  LBOX: "Lockbox Transactions",
  LFUT: "Listed Derivatives - Futures",
  LOCT: "Stand-By Letter Of Credit",
  LOPT: "Listed Derivatives - Options",
  MCOP: "Miscellaneous Credit Operations",
  MCRD: "Merchant Card Transactions",
  MDOP: "Miscellaneous Debit Operations",
  MGLN: "Mortgage Loans",
  NDFX: "Non Deliverable",
  NSET: "Non Settled",
  NTAV: "Not Available",
  NTDP: "Notice Deposits",
  NTLN: "Notice Loans",
  OBND: "OTC Derivatives - Bonds",
  OCRD: "OTC Derivatives - Credit",
  OEQT: "OTC Derivatives - Equity",
  OIRT: "OTC Derivatives - Interest Rates",
  OPCL: "Opening & Closing",
  OPTN: "Options",
  OSED: "OTC Derivatives - Structured Exotic Derivatives",
  OSWP: "OTC Derivatives – Swaps",
  OTHB: "CSD Blocked Transactions",
  OTHR: "Other",
  RCCN: "Received Cash Concentration Transactions",
  RCDT: "Received Credit Transfers",
  RCHQ: "Received Cheques",
  RDDT: "Received Direct Debits",
  RRCT: "Received Real-Time Credit Transfers",
  SETT: "Trade, Clearing and Settlement",
  SPOT: "Spots",
  SWAP: "Swaps",
  SYDN: "Syndications",
};

/** ISO BTC SubFamily codes (ExternalBankTransactionSubFamily1Code). */
export const BTC_SUBFAMILIES: Record<string, string> = {
  ACCC: "Account Closing",
  ACCO: "Account Opening",
  ACCT: "Account Transfer",
  ACDT: "ACH Credit",
  ACON: "ACH Concentration",
  ACOR: "ACH Corporate Trade",
  ADBT: "ACH Debit",
  ADJT: "Adjustments",
  APAC: "ACH Pre-Authorised",
  ARET: "ACH Return",
  AREV: "ACH Reversal",
  ARPD: "ARP Debit",
  ASET: "ACH Settlement",
  ATXN: "ACH Transaction",
  AUTT: "Automatic Transfer",
  BACT: "Branch Account Transfer",
  BBDD: "SEPA B2B Direct Debit",
  BCDP: "Branch Deposit",
  BCHQ: "Bank Cheque",
  BCKV: "Back Value",
  BCWD: "Branch Withdrawal",
  BIDS: "Repurchase Offer / Issuer Bid / Reverse Rights",
  BKFE: "Bank Fees",
  BONU: "Bonus Issue / Capitalisation Issue",
  BOOK: "Internal Book Transfer",
  BPUT: "Put Redemption",
  BROK: "Brokerage Fee",
  BSBC: "Sell Buy Back",
  BSBO: "Buy Sell Back",
  CAJT: "Credit Adjustments",
  CAPG: "Capital Gains Distribution",
  CASH: "Cash Letter",
  CCCH: "Certified Customer Cheque",
  CCHQ: "Cheque",
  CCSM: "CCP Cleared Segregated Initial Margin",
  CDIS: "Controlled Disbursement",
  CDPT: "Cash Deposit",
  CHAR: "Charge / Fees",
  CHKD: "Check Deposit",
  CHRG: "Charges",
  CLAI: "Compensation / Claims",
  CLCQ: "Circular Cheque",
  CMBO: "Corporate Mark Broker Owned",
  CMCO: "Corporate Mark Client Owned",
  COAT: "Corporate Own Account Transfer",
  COME: "Commission Excluding Taxes",
  COMI: "Commission Including Taxes",
  COMM: "Commission",
  COMT: "Non Taxable Commissions",
  CONV: "Conversion",
  COVE: "Cover Transaction",
  CPEN: "Cash Penalties",
  CPRB: "Corporate Rebate",
  CQRV: "Cheque Reversal",
  CRCQ: "Crossed Cheque",
  CROS: "Cross Trade",
  CSHA: "Cash Letter Adjustment",
  CSLI: "Cash In Lieu",
  CWDL: "Cash Withdrawal",
  DAJT: "Debit Adjustments",
  DDFT: "Discounted Draft",
  DDWN: "Drawdown",
  DECR: "Decrease in Value",
  DMCG: "Draft Maturity Change",
  DMCT: "Domestic Credit Transfer",
  DPST: "Deposit",
  DRAW: "Drawing",
  DRIP: "Dividend Reinvestment",
  DSBR: "Controlled Disbursement",
  DTCH: "Dutch Auction",
  DVCA: "Cash Dividend",
  DVOP: "Dividend Option",
  ENCT: "Nordic Payment Council Credit Transfer",
  EQBO: "Equity Mark Broker Owned",
  EQCO: "Equity Mark Client Owned",
  ERTA: "Exchange Rate Adjustment",
  ERWA: "Lending Income",
  ERWI: "Borrowing Fee",
  ESCT: "SEPA Credit Transfer",
  ESDD: "SEPA Core Direct Debit",
  EXOF: "Exchange",
  EXRI: "Call On Intermediate Securities",
  EXWA: "Warrant Exercise / Warrant Conversion",
  FCDP: "Foreign Currencies Deposit",
  FCTA: "Factor Update",
  FCWD: "Foreign Currencies Withdrawal",
  FEES: "Fees",
  FICT: "Financial Institution Credit Transfer",
  FIDD: "Financial Institution Direct Debit Payment",
  FIOA: "Financial Institution Own Account Transfer",
  FLTA: "Float Adjustment",
  FRZF: "Freeze Of Funds",
  FUCO: "Futures Commission",
  FUTU: "Future Variation Margin",
  FWBC: "Forwards Broker Owned Collateral",
  FWCC: "Forwards Client Owned Collateral",
  FWSB: "MFA Segregated Broker Cash Collateral",
  FWSC: "MFA Segregated Client Cash Collateral",
  GEN1: "Withdrawal / Distribution",
  GEN2: "Deposit / Contribution",
  IADD: "Invoice Accepted with Deferred Due Date",
  ICCT: "Intra Company Transfer",
  INFD: "Fixed Deposit Interest Amount",
  INSP: "Inspeci / Share Exchange",
  INTR: "Interest Payment",
  ISSU: "Depositary Receipt Issue",
  LBCA: "Credit Adjustment",
  LBDB: "Debit",
  LBDP: "Deposit",
  LIQU: "Liquidation Dividend / Liquidation Payment",
  MARG: "Margin Payments",
  MBSB: "Mortgage Back Segregated Broker Cash Collateral",
  MBSC: "Mortgage Back Segregated Client Cash Collateral",
  MCAL: "Full Call / Early Redemption",
  MGCC: "Margin Client Owned Cash Collateral",
  MGSC: "Initial Futures Margin Segregated Client Cash Collateral",
  MIXD: "Mixed Deposit",
  MNFE: "Management Fees",
  MRGR: "Merger",
  MSCD: "Miscellaneous Deposit",
  NETT: "Netting",
  NPCC: "Non Presented Circular Cheques",
  NSYN: "Non Syndicated",
  NTAV: "Not Available",
  NWID: "New Issue Distribution",
  ODFT: "Overdraft",
  ODLT: "Odd Lot Sale / Purchase",
  OODD: "One-Off Direct Debit",
  OPBC: "Option Broker Owned Collateral",
  OPCC: "Option Client Owned Collateral",
  OPCQ: "Open Cheque",
  OPSB: "OTC Option Segregated Broker Cash Collateral",
  OPSC: "OTC Option Segregated Client Cash Collateral",
  ORCQ: "Order Cheque",
  OTCC: "OTC CCP",
  OTCG: "OTC",
  OTCN: "OTC Non-CCP",
  OTHR: "Other",
  OVCH: "Overdraft Charge",
  OWNE: "External Account Transfer",
  OWNI: "Internal Account Transfer",
  PADD: "Pre-Authorised Direct Debit",
  PAIR: "Pair-Off",
  PCAL: "Partial Redemption With Reduction Of Nominal Value",
  PLAC: "Placement",
  PMDD: "Direct Debit Payment",
  PORT: "Portfolio Move",
  POSC: "Credit Card Payment",
  POSD: "Point-of-Sale Payment - Debit Card",
  POSP: "Point-of-Sale Payment",
  PPAY: "Principal Payment",
  PRCT: "Priority Credit Transfer",
  PRDD: "Reversal Due To Payment Reversal",
  PRED: "Partial Redemption Without Reduction Of Nominal Value",
  PRII: "Interest Payment with Principles",
  PRIN: "Interest Payment with Principles",
  PRIO: "Priority Issue",
  PRUD: "Principal Pay-down / Pay-up",
  PSTE: "Posting Error",
  RCDD: "Reversal Due To Payment Cancellation Request",
  RCOV: "Reversal Due To Cover Transaction Return",
  REAA: "Redemption Asset Allocation",
  REDM: "Final Maturity",
  REPU: "Repo",
  RESI: "Futures Residual Amount",
  RHTS: "Rights Issue / Subscription Rights / Rights Offer",
  RIMB: "Reimbursement",
  RNEW: "Renewal",
  RPCR: "Reversal Due To Payment Cancellation Request",
  RPMT: "Repayment",
  RPSB: "Bi-lateral Repo Segregated Broker Cash Collateral",
  RPSC: "Bi-lateral Repo Segregated Client Cash Collateral",
  RRTN: "Reversal Due To Payment Return",
  RVPO: "Reverse Repo",
  RWPL: "Redemption Withdrawing Plan",
  SABG: "Settlement Against Bank Guarantee",
  SALA: "Payroll / Salary Payment",
  SDVA: "Same Day Value Credit Transfer",
  SECB: "Securities Borrowing",
  SECL: "Securities Lending",
  SHPR: "Equity Premium Reserve",
  SLBC: "Lending Broker Owned Cash Collateral",
  SLCC: "Lending Client Owned Cash Collateral",
  SMRT: "Smart-Card Payment",
  SOSE: "Settlement Of Sight Export Document",
  SOSI: "Settlement Of Sight Import Document",
  SSPL: "Subscription Savings Plan",
  STAC: "Settlement After Collection",
  STAM: "Settlement At Maturity",
  STDO: "Standing Order",
  STLM: "Settlement",
  STLR: "Settlement Under Reserve",
  STOD: "Bill of Exchange Settlement on Demand",
  SUAA: "Subscription Asset Allocation",
  SUBS: "Subscription",
  SWAP: "Swap Payment",
  SWBC: "Swap Broker Owned Collateral",
  SWCC: "Swap Client Owned Cash Collateral",
  SWEP: "Sweeping",
  SWFP: "Final Payment",
  SWIC: "Switch",
  SWPP: "Partial Payment",
  SWRS: "Reset Payment",
  SWSB: "ISDA/CSA Segregated Broker Cash Collateral",
  SWSC: "ISDA/CSA Segregated Client Cash Collateral",
  SWUF: "Upfront Payment",
  SYND: "Syndicated",
  TAXE: "Taxes",
  TBAC: "TBA Closing",
  TCDP: "Travellers Cheques Deposit",
  TCWD: "Travellers Cheques Withdrawal",
  TEND: "Tender",
  TOPG: "Topping",
  TOUT: "Transfer Out",
  TRAD: "Trade",
  TREC: "Tax Reclaim",
  TRFE: "Transaction Fees",
  TRIN: "Transfer In",
  TRPO: "Triparty Repo",
  TRVO: "Triparty Reverse Repo",
  TTLS: "Treasury Tax And Loan Service",
  TURN: "Turnaround",
  UDFT: "Dishonoured / Unpaid Draft",
  UNCO: "Underwriting Commission",
  UPCQ: "Unpaid Cheque",
  UPCT: "Unpaid Card Transaction",
  UPDD: "Reversal Due To Return / Unpaid Direct Debit",
  URCQ: "Cheque Under Reserve",
  URDD: "Direct Debit Under Reserve",
  VALD: "Value Date",
  VCOM: "Credit Transfer With Agreed Commercial Information",
  WITH: "Withholding Tax",
  XBCP: "Cross-Border Credit Card Payment",
  XBCQ: "Foreign Cheque",
  XBCT: "Cross-Border Credit Transfer",
  XBCW: "Cross-Border Cash Withdrawal",
  XBDD: "Cross-Border Direct Debit",
  XBRD: "Cross-Border",
  XBSA: "Cross-Border Payroll / Salary Payment",
  XBST: "Cross-Border Standing Order",
  XCHC: "Exchange Traded CCP",
  XCHG: "Exchange Traded",
  XCHN: "Exchange Traded Non-CCP",
  XICT: "Cross-Border Intra Company Transfer",
  XPCQ: "Unpaid Foreign Cheque",
  XRCQ: "Foreign Cheque Under Reserve",
  XRTN: "Cross-Border Reversal Due To Payment Return",
  YTDA: "YTD Adjustment",
  ZABA: "Zero Balancing",
};

/**
 * German descriptions per Domain code (derived from UniCredit GVC table).
 * The three levels can be used independently for generic category labels.
 */
export const BTC_DOMAINS_DE: Record<string, string> = {
  ACMT: "Kontoverwaltung",
  CAMT: "Cash Management",
  CMDT: "Rohstoffe",
  DERV: "Derivate",
  FORX: "Devisen",
  LDAS: "Kredite, Einlagen & Syndizierungen",
  PMET: "Edelmetalle",
  PMNT: "Zahlungsverkehr",
  SECU: "Wertpapiere",
  TRAD: "Handelsfinanzierung",
  XTND: "Sonstige",
};

/** German descriptions per Family code (derived from UniCredit GVC table). */
export const BTC_FAMILIES_DE: Record<string, string> = {
  ACOP: "Sonstige Gutschriftsoperationen",
  ADOP: "Sonstige Belastungsoperationen",
  BLOC: "Gesperrte Transaktionen",
  CAPL: "Cash Pooling",
  CCRD: "Kundenkartentransaktionen",
  CNTR: "Kassenzähler / Kassentransaktionen",
  CORP: "Kapitalmaßnahme",
  CSLN: "Verbraucherkredite",
  CUST: "Depotführung",
  DRFT: "Wechsel",
  FTDP: "Termingeldeinlagen",
  FTLN: "Terminkredite",
  FTUR: "Futures",
  FWRD: "Devisentermingeschäfte",
  GUAR: "Garantien / Aval",
  ICCN: "Ausgehende Konzentrationsaufträge",
  ICDT: "Ausgehende Überweisungen",
  ICHQ: "Ausgestellte Schecks",
  IDDT: "Ausgehende Lastschriften",
  IRCT: "Ausgehende Echtzeitüberweisungen",
  MCOP: "Sonstige Gutschriftsvorgänge",
  MCRD: "Händlerkartentransaktionen",
  MDOP: "Sonstige Belastungsvorgänge",
  NTAV: "Nicht verfügbar",
  OPCL: "Kontoeröffnung und -schließung",
  OTHR: "Sonstige",
  RCCN: "Eingehende Konzentrationsaufträge",
  RCDT: "Eingehende Überweisungen",
  RCHQ: "Eingereichte Schecks",
  RDDT: "Eingehende Lastschriften",
  RRCT: "Eingehende Echtzeitüberweisungen",
  SETT: "Handel, Clearing und Abrechnung",
  SPOT: "Kassengeschäfte",
};

/** German descriptions per SubFamily code (derived from UniCredit GVC table). */
export const BTC_SUBFAMILIES_DE: Record<string, string> = {
  ACCC: "Kontoschließung",
  BBDD: "SEPA-Firmenlastschrift (B2B)",
  BOOK: "Buchinterner Transfer / Kontoübertrag",
  CCHQ: "Inhaberscheck / Reisescheck",
  CDPT: "Einzahlung",
  CHRG: "Entgelt / Gebühr",
  COMM: "Provision",
  CWDL: "Barabhebung",
  DAJT: "Belastungskorrektur",
  DPST: "Anlage (Termingeld)",
  DVCA: "Bardividende / Zinsgutschrift",
  ESCT: "SEPA-Überweisung",
  ESDD: "SEPA-Basislastschrift (CORE)",
  FCDP: "Fremdwährungseinzahlung",
  INTR: "Zinsen",
  NTAV: "Nicht verfügbar",
  OODD: "Einmalige Lastschrift",
  ORCQ: "Orderscheck",
  OTHR: "Sonstige",
  POSC: "Kreditkartenzahlung",
  POSD: "POS-Zahlung (Debitkarte)",
  POSP: "POS-Zahlung",
  PSTE: "Storno",
  RCDD: "Storno (Zahlungsstornierung)",
  RIMB: "Rückerstattung",
  RPMT: "Rückzahlung",
  RRTN: "Rücküberweisung",
  SALA: "Gehalts- / Rentenzahlung",
  SDVA: "Eilüberweisung (gleichtägig)",
  SMRT: "Geldkartentransaktion",
  STAM: "Abrechnung bei Fälligkeit",
  STDO: "Dauerauftrag",
  STLR: "Abrechnung unter Vorbehalt",
  TRAD: "Wertpapierhandel",
  UPCQ: "Unbezahlter Scheck",
  UPCT: "Unbezahlte Kartentransaktion",
  UPDD: "Rückgabe / Widerspruch Lastschrift",
  URCQ: "Scheck unter Vorbehalt",
  XBCT: "Grenzüberschreitende Überweisung",
  XBST: "Grenzüberschreitender Dauerauftrag",
  XRTN: "Rücküberweisung (grenzüberschreitend)",
};

/**
 * German booking texts for specific (Domain/Family/SubFamily) combinations
 * as used in the German banking practice (source: UniCredit GVC table, August 2022).
 *
 * Key format: `"DOMAIN/FAMILY/SUBFAMILY"` (all uppercase).
 * Not all possible combinations are present — only those actually defined by UniCredit.
 * Fall back to per-level lookups when a combination is absent.
 */
export const BTC_COMBINATIONS_DE: Record<string, string> = {
  // ACMT - Kontoverwaltung
  "ACMT/ACOP/PSTE": "Storno",
  "ACMT/MCOP/CHRG": "Entgelt",
  "ACMT/MCOP/COMM": "Preise / Entgelte",
  "ACMT/MCOP/INTR": "Zinsen",
  "ACMT/MDOP/CHRG": "Kartenpreis / Entgelt",
  "ACMT/MDOP/COMM": "Preise / Entgelte",
  "ACMT/MDOP/INTR": "Eingeräumte Kontoüberziehung",
  "ACMT/OPCL/ACCC": "Abschluss",
  // CAMT - Cash Management
  "CAMT/CAPL/OTHR": "Saldoberichtigung / Cash-Pooling-Übertrag",
  // DERV - Derivate
  "DERV/OTHR/OTHR": "Derivatebuchung",
  // FORX - Devisen
  "FORX/FWRD/OTHR": "Devisentermin-Kauf / -Verkauf",
  "FORX/SPOT/OTHR": "Devisenkassa-Kauf / -Verkauf",
  // LDAS - Kredite und Einlagen
  "LDAS/FTDP/DPST": "Termingeld (Anlage)",
  "LDAS/FTDP/RPMT": "Termingeld (Rückzahlung)",
  "LDAS/MCOP/CHRG": "Kreditprovision",
  "LDAS/MDOP/CHRG": "Kreditprovision",
  // PMET - Edelmetalle
  "PMET/SPOT/OTHR": "Edelmetall-Abrechnung",
  // PMNT/CCRD - Kundenkartentransaktionen
  "PMNT/CCRD/CWDL": "Kartenauszahlung (SEPA Card Clearing)",
  "PMNT/CCRD/OTHR": "Kartentransaktion (SEPA Card Clearing)",
  "PMNT/CCRD/POSC": "Kreditkartenabrechnung",
  "PMNT/CCRD/POSD": "POS-Kartenzahlung (SEPA Card Clearing)",
  "PMNT/CCRD/RIMB": "SEPA Cards Clearing (Wiedergutschrift)",
  "PMNT/CCRD/SMRT": "Laden Geldkarte (SEPA Card Clearing)",
  // PMNT/CNTR - Kassenzähler
  "PMNT/CNTR/CDPT": "Einzahlung",
  "PMNT/CNTR/CWDL": "Barscheck / Bargeldauszahlung",
  "PMNT/CNTR/FCDP": "Wechseldiskontierung",
  // PMNT/DRFT - Wechsel
  "PMNT/DRFT/STAM": "Wechsel-Inkasso (Import)",
  "PMNT/DRFT/STLR": "Wechsel-Inkasso (Export)",
  // PMNT/ICDT - Ausgehende Überweisungen
  "PMNT/ICDT/BOOK": "Kontoübertrag / Saldo (Belastung)",
  "PMNT/ICDT/ESCT": "Überweisung (Einzelbuchung)",
  "PMNT/ICDT/RRTN": "SEPA-Rückgabe (Retoure / Rückruf) einer Überweisung",
  "PMNT/ICDT/SDVA": "Eilüberweisung",
  "PMNT/ICDT/STDO": "Dauerauftrag (Ausführung)",
  "PMNT/ICDT/XBCT": "Auslandszahlungsverkehr (Belastung)",
  "PMNT/ICDT/XBST": "Auslandsdauerauftrag",
  "PMNT/ICDT/XRTN": "Auslandszahlungsverkehr (Wiedergutschrift)",
  // PMNT/ICHQ - Ausgestellte Schecks
  "PMNT/ICHQ/CCHQ": "Inhaberscheck / Reisescheck",
  "PMNT/ICHQ/ESCT": "Zahlungsanweisung zur Verrechnung",
  "PMNT/ICHQ/ORCQ": "Orderscheck",
  "PMNT/ICHQ/UPCQ": "Scheckrückgabe",
  // PMNT/IDDT - Ausgehende Lastschriften (Einreichung)
  "PMNT/IDDT/BBDD": "SEPA-Firmenlastschrift, Eingang vorbehalten (B2B)",
  "PMNT/IDDT/ESDD": "SEPA-Basislastschrift (CORE, Einzelbuchung)",
  "PMNT/IDDT/RCDD": "SEPA-Lastschrift, reversal",
  "PMNT/IDDT/UPDD": "SEPA-Lastschrift-Rückgabe (B2B, Einzelbuchung)",
  // PMNT/IRCT - Ausgehende Echtzeitüberweisungen
  "PMNT/IRCT/ESCT": "Echtzeitüberweisung",
  "PMNT/IRCT/RRTN": "Rücküberweisung aus Echtzeitüberweisung (Einzelbuchung)",
  // PMNT/MCOP / PMNT/MDOP - Sonstige Gutschriften / Belastungen
  "PMNT/MCOP/OTHR": "Gutschrift",
  "PMNT/MCRD/CHRG": "Entgelteinzug Geldkarte",
  "PMNT/MCRD/DAJT": "SEPA Cards Clearing (Reversal)",
  "PMNT/MCRD/POSP": "POS Gutschrift",
  "PMNT/MCRD/UPCT": "SEPA Cards Clearing (Rückbelastung)",
  "PMNT/MDOP/OTHR": "Belastung",
  // PMNT/RCDT - Eingehende Überweisungen
  "PMNT/RCDT/BOOK": "Kontoübertrag / Saldo (Gutschrift)",
  "PMNT/RCDT/ESCT": "SEPA-Gutschrift (Einzelbuchung)",
  "PMNT/RCDT/SALA": "SEPA-Gehalts- / Pensionsgutschrift",
  "PMNT/RCDT/SDVA": "Eilüberweisung Gutschrift",
  "PMNT/RCDT/STDO": "SEPA-Dauerauftragsgutschrift (Einzelbuchung)",
  "PMNT/RCDT/XBCT": "Auslandszahlungsverkehr (Gutschrift)",
  // PMNT/RCHQ - Eingereichte Schecks
  "PMNT/RCHQ/UPCQ": "Scheckrückgabe",
  "PMNT/RCHQ/URCQ": "Scheckeinreichung unter Vorbehalt",
  // PMNT/RDDT - Eingehende Lastschriften (Belastung)
  "PMNT/RDDT/BBDD": "SEPA-Firmenlastschrift (B2B, Einzelbuchung-Soll)",
  "PMNT/RDDT/ESDD": "SEPA-Basislastschrift (CORE, Einzelbuchung-Soll)",
  "PMNT/RDDT/OODD": "Überweisung (PayDirekt)",
  "PMNT/RDDT/UPDD": "SEPA-Lastschrift-Rückgabe (CORE, Wiedergutschrift)",
  // PMNT/RRCT - Eingehende Echtzeitüberweisungen
  "PMNT/RRCT/ESCT": "Echtzeitüberweisung (Gutschrift)",
  "PMNT/RRCT/RRTN": "Rücküberweisung aus Echtzeitüberweisung (Reject)",
  "PMNT/RRCT/SALA": "Echtzeit Gehalts- / Pensionsgutschrift",
  // SECU - Wertpapiere
  "SECU/CUST/CHRG": "Depotpreise Gebühr",
  "SECU/CUST/DVCA": "Zinsgutschrift / Dividende",
  "SECU/SETT/TRAD": "Effekten",
  // TRAD - Handelsfinanzierung
  "TRAD/GUAR/OTHR": "Aval",
  "TRAD/MCOP/COMM": "Provision Wertpapierleihegeschäft (Gutschrift)",
  "TRAD/MDOP/COMM": "Provision Wertpapierleihegeschäft (Belastung)",
  // XTND - Sonstige
  "XTND/NTAV/NTAV": "Kontoschließung / Sonstige",
};

/**
 * Returns the human-readable description for an ISO BTC code.
 *
 * @param level - Which level to look up.
 * @param code  - The 4-letter code, case-insensitive.
 * @param lang  - "en" (default) or "de".
 * @returns The description string, or `undefined` if the code is unknown.
 */
export function lookupBtcCode(
  level: "domain" | "family" | "subfamily",
  code: string | null | undefined,
  lang: "en" | "de" = "en",
): string | undefined {
  if (!code) return undefined;
  const key = code.trim().toUpperCase();
  if (lang === "de") {
    switch (level) {
      case "domain":    return BTC_DOMAINS_DE[key];
      case "family":    return BTC_FAMILIES_DE[key];
      case "subfamily": return BTC_SUBFAMILIES_DE[key];
    }
  }
  switch (level) {
    case "domain":    return BTC_DOMAINS[key];
    case "family":    return BTC_FAMILIES[key];
    case "subfamily": return BTC_SUBFAMILIES[key];
  }
}

/**
 * Returns the German booking text for a specific (Domain, Family, SubFamily) triple
 * from the UniCredit GVC table.
 *
 * Falls back to the per-level German description if the combination is not listed,
 * then to English, then to `undefined`.
 *
 * @param domain    - Domain code (e.g. "PMNT"), case-insensitive.
 * @param family    - Family code (e.g. "RCDT"), case-insensitive.
 * @param subfamily - SubFamily code (e.g. "ESCT"), case-insensitive.
 */
export function lookupBtcCombination(
  domain: string | null | undefined,
  family: string | null | undefined,
  subfamily: string | null | undefined,
): string | undefined {
  if (!domain || !family || !subfamily) return undefined;
  const key = `${domain.trim().toUpperCase()}/${family.trim().toUpperCase()}/${subfamily.trim().toUpperCase()}`;
  return BTC_COMBINATIONS_DE[key];
}
