-- Migration 0030: Rueckblicke (recaps).
--
-- Auto-generated photo retrospectives (equivalent to Apple/Google "Memories",
-- locally branded "Rueckblicke"). Each recap groups a curated set of photos
-- under a narrative title and cover image. Recaps are regenerated by a daily
-- cron job; users can dismiss individual recaps to hide them.

CREATE TYPE recap_kind AS ENUM (
  'on_this_day',
  'trip',
  'person',
  'place',
  'theme',
  'recent_highlights'
);--> statement-breakpoint

CREATE TABLE recaps (
  id              SERIAL PRIMARY KEY,
  user_id         INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  kind            recap_kind NOT NULL,
  title           TEXT NOT NULL,
  subtitle        TEXT,
  cover_photo_id  INTEGER REFERENCES photos(id) ON DELETE SET NULL,
  period_start    TIMESTAMP,
  period_end      TIMESTAMP,
  score           REAL NOT NULL DEFAULT 0,
  -- Deduplication key: same logical recap (same trip window, same "on this
  -- day" date, etc.) must not be re-created on every cron run. Builders
  -- derive a stable slug per recap; UNIQUE per user.
  dedup_key       TEXT NOT NULL,
  -- Frozen snapshot of the seed parameters so we can show the user WHY a
  -- recap was generated (e.g. { "location_city": "Rom", "years_ago": 1 }).
  seed            JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
  dismissed_at    TIMESTAMP
);--> statement-breakpoint

CREATE UNIQUE INDEX uq_recaps_user_dedup ON recaps (user_id, dedup_key);--> statement-breakpoint
CREATE INDEX idx_recaps_user_created ON recaps (user_id, created_at DESC);--> statement-breakpoint
CREATE INDEX idx_recaps_user_visible
  ON recaps (user_id, score DESC)
  WHERE dismissed_at IS NULL;--> statement-breakpoint

CREATE TABLE recap_photos (
  recap_id   INTEGER NOT NULL REFERENCES recaps(id) ON DELETE CASCADE,
  photo_id   INTEGER NOT NULL REFERENCES photos(id) ON DELETE CASCADE,
  rank       INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (recap_id, photo_id)
);--> statement-breakpoint

CREATE INDEX idx_recap_photos_recap ON recap_photos (recap_id, rank);
